name = "HungryHIPPO"
uuid = "bc49cf77-bdf8-43cc-9e94-9655b63242a6"
authors = ["Bijan Jourabchi"]
version = "1.0.0-DEV"

[deps]
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"

[compat]
ImageFiltering = "0.7.10"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
